config/routes.rb
Rails.application.routes.draw do
  root 'pages#welcome'
  get '/portfolio' => 'pages#portfolio'
  get '/welcome' => 'pages#welcome'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
    
  end
  def portfolio
  
end
end

app/controllers/portfolio_page_controller.rb
class PortfolioPageController < ApplicationController
end
def portfolio
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolio_page_helper.rb
module PortfolioPageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
  <link href='https://fonts.googleapis.com/css?family=Roboto:100,300,500,700' rel='stylesheet' type='text/css'>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="header">
  <div class="container">
		<div class="row">
			<div class="menu col-xs-8">
				<ul> <li><%= link_to 'Welcome', welcome_path %></li> <li><%= link_to 'Portfolio', portfolio_path %></li> <li><a href="https://medium.com/about-codecademy">Blog</a></li> <li><a href="about">About</a></li> <li><a href="contact">Contact</a></li> </ul>
      </div>
    </div>
  </div>
</div>
  
<%= yield %>

  <div class="footer">
  <div class="container">
    <ul class="social_media"> <li><a class="github" href="#">github</a></li> <li><a class="linkedin" href="#">linkedin</a></li> <li><a class="twitter" href="#">twitter</a></li> </ul>
  </div>
</div>
  
</body>
</html>

app/views/pages/welcome.html.erb
<div class="header">
  <div class="container">
		<div class="row">
			<div class="menu col-xs-8">
				<ul> <li><a href="/">Welcome</a></li> <li><%= link_to 'Welcome', welcome_path %></li> <li><a href="https://medium.com/about-codecademy">Blog</a></li> <li><a href="about">About</a></li> <li><a href="contact">Contact</a></li> </ul>
      </div>
    </div>
  </div>
</div>
<div class="main home">
  <div class="jumbotron">
		<div class="container">
      <h2>Hi my name is Charis(Bob) Rafailidis and I am an all-around internet player</h2><a class="btn right" href="portfolio">View my Work</a>
    </div>
  </div>
</div>
<div class="footer">
  <div class="container">
    <ul class="social_media"> <li><a class="github" href="#">github</a></li> <li><a class="linkedin" href="#">linkedin</a></li> <li><a class="twitter" href="#">twitter</a></li> </ul>
  </div>
</div>